/* automatically generated from process-window.ui */
#ifdef __SUNPRO_C
#pragma align 4 (process_window_ui)
#endif
#ifdef __GNUC__
static const char process_window_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char process_window_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><object class=\"GtkWindow\" id=\"proc"
  "ess-window\"><property name=\"title\" translatable=\"yes\">Task Manager"
  "</property><property name=\"default_width\">490</property><property nam"
  "e=\"default_height\">465</property><property name=\"icon_name\">utiliti"
  "es-system-monitor</property><child><object class=\"GtkVBox\" id=\"proce"
  "ss-vbox\"><property name=\"visible\">True</property><property name=\"or"
  "ientation\">vertical</property><child><object class=\"GtkToolbar\" id=\""
  "process-toolbar\"><property name=\"visible\">True</property><property n"
  "ame=\"toolbar_style\">both</property><property name=\"show_arrow\">Fals"
  "e</property><property name=\"icon_size\">1</property><child><object cla"
  "ss=\"GtkToolButton\" id=\"toolbutton-execute\"><property name=\"visible"
  "\">True</property><property name=\"is_important\">True</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"stock_id\">g"
  "tk-execute</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"homogeneous\">True</property></packing></chi"
  "ld><child><object class=\"GtkToolButton\" id=\"toolbutton-preferences\""
  "><property name=\"visible\">True</property><property name=\"is_importan"
  "t\">True</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"stock_id\">gtk-preferences</property></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"homogeneous\">T"
  "rue</property></packing></child><child><object class=\"GtkToolItem\" id"
  "=\"cpu-toolitem\"><property name=\"visible\">True</property><property n"
  "ame=\"border_width\">2</property><child><placeholder/></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"homo"
  "geneous\">True</property></packing></child><child><object class=\"GtkTo"
  "olItem\" id=\"mem-toolitem\"><property name=\"visible\">True</property>"
  "<property name=\"border_width\">2</property><child><placeholder/></chil"
  "d></object><packing><property name=\"expand\">True</property><property "
  "name=\"homogeneous\">True</property></packing></child><child><object cl"
  "ass=\"GtkToolButton\" id=\"toolbutton-about\"><property name=\"visible\""
  ">True</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"stock_id\">gtk-about</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"homogeneous\">True</prop"
  "erty></packing></child><child><object class=\"GtkToolButton\" id=\"tool"
  "button-quit\"><property name=\"visible\">True</property><property name="
  "\"is_important\">True</property><property name=\"use_underline\">True</"
  "property><property name=\"stock_id\">gtk-quit</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"homogeneo"
  "us\">True</property></packing></child></object><packing><property name="
  "\"expand\">False</property><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkVBox\" id=\"root-warning-box\">"
  "<property name=\"orientation\">vertical</property><child><object class="
  "\"GtkEventBox\" id=\"root-warning-ebox\"><property name=\"visible\">Tru"
  "e</property><child><object class=\"GtkLabel\" id=\"root-warning-label\""
  "><property name=\"visible\">True</property><property name=\"xpad\">6</p"
  "roperty><property name=\"ypad\">3</property><property name=\"label\" tr"
  "anslatable=\"yes\">Warning, you are using the root account, you may har"
  "m your system.</property></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">0</property></packing></child><child><objec"
  "t class=\"GtkHSeparator\" id=\"root-warning-separator\"><property name="
  "\"visible\">True</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">1</property"
  "></packing></child><child><object class=\"GtkVBox\" id=\"mainview-vbox\""
  "><property name=\"visible\">True</property><property name=\"border_widt"
  "h\">6</property><property name=\"orientation\">vertical</property><prop"
  "erty name=\"spacing\">6</property><child><object class=\"GtkScrolledWin"
  "dow\" id=\"scrolledwindow\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"hscrollbar_"
  "policy\">automatic</property><property name=\"vscrollbar_policy\">autom"
  "atic</property><property name=\"shadow_type\">in</property><child><plac"
  "eholder/></child></object><packing><property name=\"position\">0</prope"
  "rty></packing></child></object><packing><property name=\"position\">2</"
  "property></packing></child><child><placeholder/></child></object></chil"
  "d></object></interface>"
};

static const unsigned process_window_ui_length = 4508u;

